
namespace DOT.GUI
{
    partial class MainWindow
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainWindow));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.p_header = new Bunifu.UI.WinForms.BunifuPanel();
            this.bttn_zoomin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bttn_zoomout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.sep_icon__title = new Bunifu.UI.WinForms.BunifuSeparator();
            this.pb_header = new System.Windows.Forms.PictureBox();
            this.bttn_fullscreen = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.sep_tools__windowbuttons = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bttn_mini = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bttn_maxmini = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bttn_exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.snackbar = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.MainFrame = new Bunifu.UI.WinForms.BunifuPanel();
            this.p_tabs = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.sep_tools = new Bunifu.UI.WinForms.BunifuSeparator();
            this.p_header.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pb_header)).BeginInit();
            this.MainFrame.SuspendLayout();
            this.SuspendLayout();
            // 
            // p_header
            // 
            this.p_header.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.p_header.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("p_header.BackgroundImage")));
            this.p_header.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.p_header.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.p_header.BorderRadius = 0;
            this.p_header.BorderThickness = 0;
            this.p_header.Controls.Add(this.sep_tools);
            this.p_header.Controls.Add(this.bunifuButton1);
            this.p_header.Controls.Add(this.bttn_zoomin);
            this.p_header.Controls.Add(this.bttn_zoomout);
            this.p_header.Controls.Add(this.label1);
            this.p_header.Controls.Add(this.sep_icon__title);
            this.p_header.Controls.Add(this.pb_header);
            this.p_header.Controls.Add(this.bttn_fullscreen);
            this.p_header.Controls.Add(this.sep_tools__windowbuttons);
            this.p_header.Controls.Add(this.bttn_mini);
            this.p_header.Controls.Add(this.bttn_maxmini);
            this.p_header.Controls.Add(this.bttn_exit);
            this.p_header.Dock = System.Windows.Forms.DockStyle.Top;
            this.p_header.Location = new System.Drawing.Point(0, 0);
            this.p_header.Margin = new System.Windows.Forms.Padding(0);
            this.p_header.Name = "p_header";
            this.p_header.Padding = new System.Windows.Forms.Padding(6, 3, 3, 3);
            this.p_header.ShowBorders = true;
            this.p_header.Size = new System.Drawing.Size(916, 32);
            this.p_header.TabIndex = 0;
            this.p_header.DoubleClick += new System.EventHandler(this.P_header_DoubleClick);
            this.p_header.MouseDown += new System.Windows.Forms.MouseEventHandler(this.P_Header_MouseDown);
            // 
            // bttn_zoomin
            // 
            this.bttn_zoomin.AllowAnimations = true;
            this.bttn_zoomin.AllowMouseEffects = true;
            this.bttn_zoomin.AllowToggling = false;
            this.bttn_zoomin.AnimationSpeed = 25;
            this.bttn_zoomin.AutoGenerateColors = false;
            this.bttn_zoomin.AutoRoundBorders = false;
            this.bttn_zoomin.AutoSizeLeftIcon = true;
            this.bttn_zoomin.AutoSizeRightIcon = true;
            this.bttn_zoomin.BackColor = System.Drawing.Color.Transparent;
            this.bttn_zoomin.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_zoomin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttn_zoomin.BackgroundImage")));
            this.bttn_zoomin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomin.ButtonText = "+";
            this.bttn_zoomin.ButtonTextMarginLeft = 0;
            this.bttn_zoomin.ColorContrastOnClick = 20;
            this.bttn_zoomin.ColorContrastOnHover = 20;
            this.bttn_zoomin.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bttn_zoomin.CustomizableEdges = borderEdges2;
            this.bttn_zoomin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttn_zoomin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_zoomin.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_zoomin.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_zoomin.Dock = System.Windows.Forms.DockStyle.Right;
            this.bttn_zoomin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bttn_zoomin.Font = new System.Drawing.Font("Ebrima", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bttn_zoomin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_zoomin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_zoomin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_zoomin.IconLeftPadding = new System.Windows.Forms.Padding(1, 0, 0, 0);
            this.bttn_zoomin.IconMarginLeft = 11;
            this.bttn_zoomin.IconPadding = 5;
            this.bttn_zoomin.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_zoomin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_zoomin.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bttn_zoomin.IconSize = 20;
            this.bttn_zoomin.IdleBorderColor = System.Drawing.Color.Black;
            this.bttn_zoomin.IdleBorderRadius = 25;
            this.bttn_zoomin.IdleBorderThickness = 1;
            this.bttn_zoomin.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_zoomin.IdleIconLeftImage = null;
            this.bttn_zoomin.IdleIconRightImage = null;
            this.bttn_zoomin.IndicateFocus = false;
            this.bttn_zoomin.Location = new System.Drawing.Point(734, 3);
            this.bttn_zoomin.Margin = new System.Windows.Forms.Padding(0);
            this.bttn_zoomin.MaximumSize = new System.Drawing.Size(26, 26);
            this.bttn_zoomin.MinimumSize = new System.Drawing.Size(26, 26);
            this.bttn_zoomin.Name = "bttn_zoomin";
            this.bttn_zoomin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_zoomin.OnDisabledState.BorderRadius = 25;
            this.bttn_zoomin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomin.OnDisabledState.BorderThickness = 1;
            this.bttn_zoomin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_zoomin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_zoomin.OnDisabledState.IconLeftImage = null;
            this.bttn_zoomin.OnDisabledState.IconRightImage = null;
            this.bttn_zoomin.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bttn_zoomin.onHoverState.BorderRadius = 25;
            this.bttn_zoomin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomin.onHoverState.BorderThickness = 1;
            this.bttn_zoomin.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_zoomin.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bttn_zoomin.onHoverState.IconLeftImage = null;
            this.bttn_zoomin.onHoverState.IconRightImage = null;
            this.bttn_zoomin.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bttn_zoomin.OnIdleState.BorderRadius = 25;
            this.bttn_zoomin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomin.OnIdleState.BorderThickness = 1;
            this.bttn_zoomin.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_zoomin.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_zoomin.OnIdleState.IconLeftImage = null;
            this.bttn_zoomin.OnIdleState.IconRightImage = null;
            this.bttn_zoomin.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bttn_zoomin.OnPressedState.BorderRadius = 25;
            this.bttn_zoomin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomin.OnPressedState.BorderThickness = 1;
            this.bttn_zoomin.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.bttn_zoomin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bttn_zoomin.OnPressedState.IconLeftImage = null;
            this.bttn_zoomin.OnPressedState.IconRightImage = null;
            this.bttn_zoomin.Size = new System.Drawing.Size(26, 26);
            this.bttn_zoomin.TabIndex = 36;
            this.bttn_zoomin.Tag = "";
            this.bttn_zoomin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttn_zoomin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttn_zoomin.TextMarginLeft = 0;
            this.bttn_zoomin.TextPadding = new System.Windows.Forms.Padding(2, -1, 3, 2);
            this.bttn_zoomin.UseDefaultRadiusAndThickness = true;
            this.bttn_zoomin.Click += new System.EventHandler(this.Bttn_zoomin_Click);
            // 
            // bttn_zoomout
            // 
            this.bttn_zoomout.AllowAnimations = true;
            this.bttn_zoomout.AllowMouseEffects = true;
            this.bttn_zoomout.AllowToggling = false;
            this.bttn_zoomout.AnimationSpeed = 25;
            this.bttn_zoomout.AutoGenerateColors = false;
            this.bttn_zoomout.AutoRoundBorders = false;
            this.bttn_zoomout.AutoSizeLeftIcon = true;
            this.bttn_zoomout.AutoSizeRightIcon = true;
            this.bttn_zoomout.BackColor = System.Drawing.Color.Transparent;
            this.bttn_zoomout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_zoomout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttn_zoomout.BackgroundImage")));
            this.bttn_zoomout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomout.ButtonText = "0";
            this.bttn_zoomout.ButtonTextMarginLeft = 0;
            this.bttn_zoomout.ColorContrastOnClick = 20;
            this.bttn_zoomout.ColorContrastOnHover = 20;
            this.bttn_zoomout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bttn_zoomout.CustomizableEdges = borderEdges3;
            this.bttn_zoomout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttn_zoomout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_zoomout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_zoomout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_zoomout.Dock = System.Windows.Forms.DockStyle.Right;
            this.bttn_zoomout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bttn_zoomout.Font = new System.Drawing.Font("Marlett", 9.75F);
            this.bttn_zoomout.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_zoomout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_zoomout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_zoomout.IconLeftPadding = new System.Windows.Forms.Padding(1, 0, 0, 0);
            this.bttn_zoomout.IconMarginLeft = 11;
            this.bttn_zoomout.IconPadding = 5;
            this.bttn_zoomout.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_zoomout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_zoomout.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bttn_zoomout.IconSize = 20;
            this.bttn_zoomout.IdleBorderColor = System.Drawing.Color.Black;
            this.bttn_zoomout.IdleBorderRadius = 25;
            this.bttn_zoomout.IdleBorderThickness = 1;
            this.bttn_zoomout.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_zoomout.IdleIconLeftImage = null;
            this.bttn_zoomout.IdleIconRightImage = null;
            this.bttn_zoomout.IndicateFocus = false;
            this.bttn_zoomout.Location = new System.Drawing.Point(760, 3);
            this.bttn_zoomout.Margin = new System.Windows.Forms.Padding(0);
            this.bttn_zoomout.MaximumSize = new System.Drawing.Size(26, 26);
            this.bttn_zoomout.MinimumSize = new System.Drawing.Size(26, 26);
            this.bttn_zoomout.Name = "bttn_zoomout";
            this.bttn_zoomout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_zoomout.OnDisabledState.BorderRadius = 25;
            this.bttn_zoomout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomout.OnDisabledState.BorderThickness = 1;
            this.bttn_zoomout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_zoomout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_zoomout.OnDisabledState.IconLeftImage = null;
            this.bttn_zoomout.OnDisabledState.IconRightImage = null;
            this.bttn_zoomout.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bttn_zoomout.onHoverState.BorderRadius = 25;
            this.bttn_zoomout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomout.onHoverState.BorderThickness = 1;
            this.bttn_zoomout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_zoomout.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bttn_zoomout.onHoverState.IconLeftImage = null;
            this.bttn_zoomout.onHoverState.IconRightImage = null;
            this.bttn_zoomout.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bttn_zoomout.OnIdleState.BorderRadius = 25;
            this.bttn_zoomout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomout.OnIdleState.BorderThickness = 1;
            this.bttn_zoomout.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_zoomout.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_zoomout.OnIdleState.IconLeftImage = null;
            this.bttn_zoomout.OnIdleState.IconRightImage = null;
            this.bttn_zoomout.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bttn_zoomout.OnPressedState.BorderRadius = 25;
            this.bttn_zoomout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_zoomout.OnPressedState.BorderThickness = 1;
            this.bttn_zoomout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.bttn_zoomout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bttn_zoomout.OnPressedState.IconLeftImage = null;
            this.bttn_zoomout.OnPressedState.IconRightImage = null;
            this.bttn_zoomout.Size = new System.Drawing.Size(26, 26);
            this.bttn_zoomout.TabIndex = 35;
            this.bttn_zoomout.Tag = "";
            this.bttn_zoomout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttn_zoomout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttn_zoomout.TextMarginLeft = 0;
            this.bttn_zoomout.TextPadding = new System.Windows.Forms.Padding(2, -2, 3, 2);
            this.bttn_zoomout.UseDefaultRadiusAndThickness = true;
            this.bttn_zoomout.Click += new System.EventHandler(this.Bttn_zoomout_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.label1.Font = new System.Drawing.Font("Sitka Small", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(118)))), ((int)(((byte)(125)))));
            this.label1.Location = new System.Drawing.Point(51, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(31, 16);
            this.label1.TabIndex = 34;
            this.label1.Text = "DOT";
            // 
            // sep_icon__title
            // 
            this.sep_icon__title.BackColor = System.Drawing.Color.Transparent;
            this.sep_icon__title.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sep_icon__title.BackgroundImage")));
            this.sep_icon__title.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sep_icon__title.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.sep_icon__title.Dock = System.Windows.Forms.DockStyle.Left;
            this.sep_icon__title.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.sep_icon__title.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.sep_icon__title.LineThickness = 1;
            this.sep_icon__title.Location = new System.Drawing.Point(32, 3);
            this.sep_icon__title.Name = "sep_icon__title";
            this.sep_icon__title.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.sep_icon__title.Size = new System.Drawing.Size(23, 26);
            this.sep_icon__title.TabIndex = 33;
            // 
            // pb_header
            // 
            this.pb_header.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pb_header.BackgroundImage")));
            this.pb_header.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pb_header.Dock = System.Windows.Forms.DockStyle.Left;
            this.pb_header.Location = new System.Drawing.Point(6, 3);
            this.pb_header.Margin = new System.Windows.Forms.Padding(0);
            this.pb_header.Name = "pb_header";
            this.pb_header.Size = new System.Drawing.Size(26, 26);
            this.pb_header.TabIndex = 32;
            this.pb_header.TabStop = false;
            // 
            // bttn_fullscreen
            // 
            this.bttn_fullscreen.AllowAnimations = true;
            this.bttn_fullscreen.AllowMouseEffects = true;
            this.bttn_fullscreen.AllowToggling = true;
            this.bttn_fullscreen.AnimationSpeed = 25;
            this.bttn_fullscreen.AutoGenerateColors = false;
            this.bttn_fullscreen.AutoRoundBorders = false;
            this.bttn_fullscreen.AutoSizeLeftIcon = true;
            this.bttn_fullscreen.AutoSizeRightIcon = true;
            this.bttn_fullscreen.BackColor = System.Drawing.Color.Transparent;
            this.bttn_fullscreen.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_fullscreen.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttn_fullscreen.BackgroundImage")));
            this.bttn_fullscreen.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_fullscreen.ButtonText = "";
            this.bttn_fullscreen.ButtonTextMarginLeft = 0;
            this.bttn_fullscreen.ColorContrastOnClick = 20;
            this.bttn_fullscreen.ColorContrastOnHover = 20;
            this.bttn_fullscreen.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bttn_fullscreen.CustomizableEdges = borderEdges4;
            this.bttn_fullscreen.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttn_fullscreen.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_fullscreen.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_fullscreen.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_fullscreen.Dock = System.Windows.Forms.DockStyle.Right;
            this.bttn_fullscreen.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bttn_fullscreen.Font = new System.Drawing.Font("Marlett", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.bttn_fullscreen.ForeColor = System.Drawing.Color.White;
            this.bttn_fullscreen.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_fullscreen.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_fullscreen.IconLeftPadding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.bttn_fullscreen.IconMarginLeft = 11;
            this.bttn_fullscreen.IconPadding = 7;
            this.bttn_fullscreen.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_fullscreen.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_fullscreen.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bttn_fullscreen.IconSize = 20;
            this.bttn_fullscreen.IdleBorderColor = System.Drawing.Color.Black;
            this.bttn_fullscreen.IdleBorderRadius = 25;
            this.bttn_fullscreen.IdleBorderThickness = 1;
            this.bttn_fullscreen.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_fullscreen.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bttn_fullscreen.IdleIconLeftImage")));
            this.bttn_fullscreen.IdleIconRightImage = null;
            this.bttn_fullscreen.IndicateFocus = true;
            this.bttn_fullscreen.Location = new System.Drawing.Point(786, 3);
            this.bttn_fullscreen.Margin = new System.Windows.Forms.Padding(0);
            this.bttn_fullscreen.MaximumSize = new System.Drawing.Size(26, 26);
            this.bttn_fullscreen.MinimumSize = new System.Drawing.Size(26, 26);
            this.bttn_fullscreen.Name = "bttn_fullscreen";
            this.bttn_fullscreen.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_fullscreen.OnDisabledState.BorderRadius = 25;
            this.bttn_fullscreen.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_fullscreen.OnDisabledState.BorderThickness = 1;
            this.bttn_fullscreen.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_fullscreen.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_fullscreen.OnDisabledState.IconLeftImage = null;
            this.bttn_fullscreen.OnDisabledState.IconRightImage = null;
            this.bttn_fullscreen.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bttn_fullscreen.onHoverState.BorderRadius = 25;
            this.bttn_fullscreen.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_fullscreen.onHoverState.BorderThickness = 1;
            this.bttn_fullscreen.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_fullscreen.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bttn_fullscreen.onHoverState.IconLeftImage = null;
            this.bttn_fullscreen.onHoverState.IconRightImage = null;
            this.bttn_fullscreen.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bttn_fullscreen.OnIdleState.BorderRadius = 25;
            this.bttn_fullscreen.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_fullscreen.OnIdleState.BorderThickness = 1;
            this.bttn_fullscreen.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_fullscreen.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bttn_fullscreen.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bttn_fullscreen.OnIdleState.IconLeftImage")));
            this.bttn_fullscreen.OnIdleState.IconRightImage = null;
            this.bttn_fullscreen.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bttn_fullscreen.OnPressedState.BorderRadius = 25;
            this.bttn_fullscreen.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_fullscreen.OnPressedState.BorderThickness = 1;
            this.bttn_fullscreen.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.bttn_fullscreen.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bttn_fullscreen.OnPressedState.IconLeftImage = null;
            this.bttn_fullscreen.OnPressedState.IconRightImage = null;
            this.bttn_fullscreen.Size = new System.Drawing.Size(26, 26);
            this.bttn_fullscreen.TabIndex = 31;
            this.bttn_fullscreen.Tag = "";
            this.bttn_fullscreen.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttn_fullscreen.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttn_fullscreen.TextMarginLeft = 0;
            this.bttn_fullscreen.TextPadding = new System.Windows.Forms.Padding(2, 0, 3, 2);
            this.bttn_fullscreen.UseDefaultRadiusAndThickness = true;
            this.bttn_fullscreen.Click += new System.EventHandler(this.Bttn_fullscreen_Click);
            // 
            // sep_tools__windowbuttons
            // 
            this.sep_tools__windowbuttons.BackColor = System.Drawing.Color.Transparent;
            this.sep_tools__windowbuttons.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sep_tools__windowbuttons.BackgroundImage")));
            this.sep_tools__windowbuttons.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sep_tools__windowbuttons.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.sep_tools__windowbuttons.Dock = System.Windows.Forms.DockStyle.Right;
            this.sep_tools__windowbuttons.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.sep_tools__windowbuttons.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.sep_tools__windowbuttons.LineThickness = 1;
            this.sep_tools__windowbuttons.Location = new System.Drawing.Point(812, 3);
            this.sep_tools__windowbuttons.Name = "sep_tools__windowbuttons";
            this.sep_tools__windowbuttons.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.sep_tools__windowbuttons.Size = new System.Drawing.Size(23, 26);
            this.sep_tools__windowbuttons.TabIndex = 30;
            // 
            // bttn_mini
            // 
            this.bttn_mini.AllowAnimations = true;
            this.bttn_mini.AllowMouseEffects = true;
            this.bttn_mini.AllowToggling = false;
            this.bttn_mini.AnimationSpeed = 25;
            this.bttn_mini.AutoGenerateColors = false;
            this.bttn_mini.AutoRoundBorders = false;
            this.bttn_mini.AutoSizeLeftIcon = true;
            this.bttn_mini.AutoSizeRightIcon = true;
            this.bttn_mini.BackColor = System.Drawing.Color.Transparent;
            this.bttn_mini.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_mini.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttn_mini.BackgroundImage")));
            this.bttn_mini.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_mini.ButtonText = "0";
            this.bttn_mini.ButtonTextMarginLeft = 0;
            this.bttn_mini.ColorContrastOnClick = 20;
            this.bttn_mini.ColorContrastOnHover = 20;
            this.bttn_mini.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bttn_mini.CustomizableEdges = borderEdges5;
            this.bttn_mini.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttn_mini.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_mini.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_mini.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_mini.Dock = System.Windows.Forms.DockStyle.Right;
            this.bttn_mini.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bttn_mini.Font = new System.Drawing.Font("Marlett", 9.75F);
            this.bttn_mini.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_mini.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_mini.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_mini.IconLeftPadding = new System.Windows.Forms.Padding(1, 0, 0, 0);
            this.bttn_mini.IconMarginLeft = 11;
            this.bttn_mini.IconPadding = 5;
            this.bttn_mini.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_mini.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_mini.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bttn_mini.IconSize = 20;
            this.bttn_mini.IdleBorderColor = System.Drawing.Color.Black;
            this.bttn_mini.IdleBorderRadius = 25;
            this.bttn_mini.IdleBorderThickness = 1;
            this.bttn_mini.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_mini.IdleIconLeftImage = null;
            this.bttn_mini.IdleIconRightImage = null;
            this.bttn_mini.IndicateFocus = false;
            this.bttn_mini.Location = new System.Drawing.Point(835, 3);
            this.bttn_mini.Margin = new System.Windows.Forms.Padding(0);
            this.bttn_mini.MaximumSize = new System.Drawing.Size(26, 26);
            this.bttn_mini.MinimumSize = new System.Drawing.Size(26, 26);
            this.bttn_mini.Name = "bttn_mini";
            this.bttn_mini.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_mini.OnDisabledState.BorderRadius = 25;
            this.bttn_mini.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_mini.OnDisabledState.BorderThickness = 1;
            this.bttn_mini.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_mini.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_mini.OnDisabledState.IconLeftImage = null;
            this.bttn_mini.OnDisabledState.IconRightImage = null;
            this.bttn_mini.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bttn_mini.onHoverState.BorderRadius = 25;
            this.bttn_mini.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_mini.onHoverState.BorderThickness = 1;
            this.bttn_mini.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_mini.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bttn_mini.onHoverState.IconLeftImage = null;
            this.bttn_mini.onHoverState.IconRightImage = null;
            this.bttn_mini.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bttn_mini.OnIdleState.BorderRadius = 25;
            this.bttn_mini.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_mini.OnIdleState.BorderThickness = 1;
            this.bttn_mini.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_mini.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_mini.OnIdleState.IconLeftImage = null;
            this.bttn_mini.OnIdleState.IconRightImage = null;
            this.bttn_mini.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bttn_mini.OnPressedState.BorderRadius = 25;
            this.bttn_mini.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_mini.OnPressedState.BorderThickness = 1;
            this.bttn_mini.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.bttn_mini.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bttn_mini.OnPressedState.IconLeftImage = null;
            this.bttn_mini.OnPressedState.IconRightImage = null;
            this.bttn_mini.Size = new System.Drawing.Size(26, 26);
            this.bttn_mini.TabIndex = 29;
            this.bttn_mini.Tag = "";
            this.bttn_mini.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttn_mini.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttn_mini.TextMarginLeft = 0;
            this.bttn_mini.TextPadding = new System.Windows.Forms.Padding(2, -2, 3, 2);
            this.bttn_mini.UseDefaultRadiusAndThickness = true;
            this.bttn_mini.Click += new System.EventHandler(this.Bttn_mini_Click);
            // 
            // bttn_maxmini
            // 
            this.bttn_maxmini.AllowAnimations = true;
            this.bttn_maxmini.AllowMouseEffects = true;
            this.bttn_maxmini.AllowToggling = false;
            this.bttn_maxmini.AnimationSpeed = 25;
            this.bttn_maxmini.AutoGenerateColors = false;
            this.bttn_maxmini.AutoRoundBorders = false;
            this.bttn_maxmini.AutoSizeLeftIcon = true;
            this.bttn_maxmini.AutoSizeRightIcon = true;
            this.bttn_maxmini.BackColor = System.Drawing.Color.Transparent;
            this.bttn_maxmini.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_maxmini.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttn_maxmini.BackgroundImage")));
            this.bttn_maxmini.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_maxmini.ButtonText = "1";
            this.bttn_maxmini.ButtonTextMarginLeft = 0;
            this.bttn_maxmini.ColorContrastOnClick = 20;
            this.bttn_maxmini.ColorContrastOnHover = 20;
            this.bttn_maxmini.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bttn_maxmini.CustomizableEdges = borderEdges6;
            this.bttn_maxmini.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttn_maxmini.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_maxmini.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_maxmini.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_maxmini.Dock = System.Windows.Forms.DockStyle.Right;
            this.bttn_maxmini.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bttn_maxmini.Font = new System.Drawing.Font("Marlett", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(2)));
            this.bttn_maxmini.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_maxmini.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_maxmini.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_maxmini.IconLeftPadding = new System.Windows.Forms.Padding(1, 0, 0, 0);
            this.bttn_maxmini.IconMarginLeft = 11;
            this.bttn_maxmini.IconPadding = 5;
            this.bttn_maxmini.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_maxmini.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_maxmini.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bttn_maxmini.IconSize = 20;
            this.bttn_maxmini.IdleBorderColor = System.Drawing.Color.Black;
            this.bttn_maxmini.IdleBorderRadius = 25;
            this.bttn_maxmini.IdleBorderThickness = 1;
            this.bttn_maxmini.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_maxmini.IdleIconLeftImage = null;
            this.bttn_maxmini.IdleIconRightImage = null;
            this.bttn_maxmini.IndicateFocus = false;
            this.bttn_maxmini.Location = new System.Drawing.Point(861, 3);
            this.bttn_maxmini.Margin = new System.Windows.Forms.Padding(0);
            this.bttn_maxmini.MaximumSize = new System.Drawing.Size(26, 26);
            this.bttn_maxmini.MinimumSize = new System.Drawing.Size(26, 26);
            this.bttn_maxmini.Name = "bttn_maxmini";
            this.bttn_maxmini.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_maxmini.OnDisabledState.BorderRadius = 25;
            this.bttn_maxmini.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_maxmini.OnDisabledState.BorderThickness = 1;
            this.bttn_maxmini.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_maxmini.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_maxmini.OnDisabledState.IconLeftImage = null;
            this.bttn_maxmini.OnDisabledState.IconRightImage = null;
            this.bttn_maxmini.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bttn_maxmini.onHoverState.BorderRadius = 25;
            this.bttn_maxmini.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_maxmini.onHoverState.BorderThickness = 1;
            this.bttn_maxmini.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_maxmini.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bttn_maxmini.onHoverState.IconLeftImage = null;
            this.bttn_maxmini.onHoverState.IconRightImage = null;
            this.bttn_maxmini.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bttn_maxmini.OnIdleState.BorderRadius = 25;
            this.bttn_maxmini.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_maxmini.OnIdleState.BorderThickness = 1;
            this.bttn_maxmini.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_maxmini.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bttn_maxmini.OnIdleState.IconLeftImage = null;
            this.bttn_maxmini.OnIdleState.IconRightImage = null;
            this.bttn_maxmini.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bttn_maxmini.OnPressedState.BorderRadius = 25;
            this.bttn_maxmini.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_maxmini.OnPressedState.BorderThickness = 1;
            this.bttn_maxmini.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.bttn_maxmini.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bttn_maxmini.OnPressedState.IconLeftImage = null;
            this.bttn_maxmini.OnPressedState.IconRightImage = null;
            this.bttn_maxmini.Size = new System.Drawing.Size(26, 26);
            this.bttn_maxmini.TabIndex = 28;
            this.bttn_maxmini.Tag = "";
            this.bttn_maxmini.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttn_maxmini.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttn_maxmini.TextMarginLeft = 0;
            this.bttn_maxmini.TextPadding = new System.Windows.Forms.Padding(2, 2, 3, 2);
            this.bttn_maxmini.UseDefaultRadiusAndThickness = true;
            this.bttn_maxmini.Click += new System.EventHandler(this.Bttn_maxmini_Click);
            // 
            // bttn_exit
            // 
            this.bttn_exit.AllowAnimations = true;
            this.bttn_exit.AllowMouseEffects = true;
            this.bttn_exit.AllowToggling = false;
            this.bttn_exit.AnimationSpeed = 25;
            this.bttn_exit.AutoGenerateColors = false;
            this.bttn_exit.AutoRoundBorders = false;
            this.bttn_exit.AutoSizeLeftIcon = true;
            this.bttn_exit.AutoSizeRightIcon = true;
            this.bttn_exit.BackColor = System.Drawing.Color.Transparent;
            this.bttn_exit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttn_exit.BackgroundImage")));
            this.bttn_exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_exit.ButtonText = "r";
            this.bttn_exit.ButtonTextMarginLeft = 0;
            this.bttn_exit.ColorContrastOnClick = 20;
            this.bttn_exit.ColorContrastOnHover = 20;
            this.bttn_exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bttn_exit.CustomizableEdges = borderEdges7;
            this.bttn_exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttn_exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_exit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_exit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.bttn_exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bttn_exit.Font = new System.Drawing.Font("Marlett", 9.25F);
            this.bttn_exit.ForeColor = System.Drawing.Color.Red;
            this.bttn_exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_exit.IconLeftPadding = new System.Windows.Forms.Padding(1, 0, 0, 0);
            this.bttn_exit.IconMarginLeft = 11;
            this.bttn_exit.IconPadding = 5;
            this.bttn_exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttn_exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttn_exit.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bttn_exit.IconSize = 20;
            this.bttn_exit.IdleBorderColor = System.Drawing.Color.Black;
            this.bttn_exit.IdleBorderRadius = 25;
            this.bttn_exit.IdleBorderThickness = 1;
            this.bttn_exit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_exit.IdleIconLeftImage = null;
            this.bttn_exit.IdleIconRightImage = null;
            this.bttn_exit.IndicateFocus = false;
            this.bttn_exit.Location = new System.Drawing.Point(887, 3);
            this.bttn_exit.Margin = new System.Windows.Forms.Padding(0);
            this.bttn_exit.MaximumSize = new System.Drawing.Size(26, 26);
            this.bttn_exit.MinimumSize = new System.Drawing.Size(26, 26);
            this.bttn_exit.Name = "bttn_exit";
            this.bttn_exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bttn_exit.OnDisabledState.BorderRadius = 25;
            this.bttn_exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_exit.OnDisabledState.BorderThickness = 1;
            this.bttn_exit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttn_exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttn_exit.OnDisabledState.IconLeftImage = null;
            this.bttn_exit.OnDisabledState.IconRightImage = null;
            this.bttn_exit.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bttn_exit.onHoverState.BorderRadius = 25;
            this.bttn_exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_exit.onHoverState.BorderThickness = 1;
            this.bttn_exit.onHoverState.FillColor = System.Drawing.Color.Orange;
            this.bttn_exit.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bttn_exit.onHoverState.IconLeftImage = null;
            this.bttn_exit.onHoverState.IconRightImage = null;
            this.bttn_exit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bttn_exit.OnIdleState.BorderRadius = 25;
            this.bttn_exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_exit.OnIdleState.BorderThickness = 1;
            this.bttn_exit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bttn_exit.OnIdleState.ForeColor = System.Drawing.Color.Red;
            this.bttn_exit.OnIdleState.IconLeftImage = null;
            this.bttn_exit.OnIdleState.IconRightImage = null;
            this.bttn_exit.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bttn_exit.OnPressedState.BorderRadius = 25;
            this.bttn_exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttn_exit.OnPressedState.BorderThickness = 1;
            this.bttn_exit.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.bttn_exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bttn_exit.OnPressedState.IconLeftImage = null;
            this.bttn_exit.OnPressedState.IconRightImage = null;
            this.bttn_exit.Size = new System.Drawing.Size(26, 26);
            this.bttn_exit.TabIndex = 26;
            this.bttn_exit.Tag = "";
            this.bttn_exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttn_exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttn_exit.TextMarginLeft = 0;
            this.bttn_exit.TextPadding = new System.Windows.Forms.Padding(1, 1, 3, 2);
            this.bttn_exit.UseDefaultRadiusAndThickness = true;
            this.bttn_exit.Click += new System.EventHandler(this.Bttn_exit_Click);
            // 
            // snackbar
            // 
            this.snackbar.AllowDragging = false;
            this.snackbar.AllowMultipleViews = true;
            this.snackbar.ClickToClose = true;
            this.snackbar.DoubleClickToClose = true;
            this.snackbar.DurationAfterIdle = 3000;
            this.snackbar.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.ErrorOptions.ActionBorderRadius = 1;
            this.snackbar.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackbar.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackbar.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.snackbar.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.snackbar.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.snackbar.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackbar.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.snackbar.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.snackbar.ErrorOptions.IconLeftMargin = 12;
            this.snackbar.FadeCloseIcon = false;
            this.snackbar.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.snackbar.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.InformationOptions.ActionBorderRadius = 1;
            this.snackbar.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackbar.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackbar.InformationOptions.BackColor = System.Drawing.Color.White;
            this.snackbar.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.snackbar.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.snackbar.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackbar.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.snackbar.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.snackbar.InformationOptions.IconLeftMargin = 12;
            this.snackbar.Margin = 10;
            this.snackbar.MaximumSize = new System.Drawing.Size(0, 0);
            this.snackbar.MaximumViews = 7;
            this.snackbar.MessageRightMargin = 15;
            this.snackbar.MinimumSize = new System.Drawing.Size(0, 0);
            this.snackbar.ShowBorders = false;
            this.snackbar.ShowCloseIcon = false;
            this.snackbar.ShowIcon = true;
            this.snackbar.ShowShadows = true;
            this.snackbar.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.SuccessOptions.ActionBorderRadius = 1;
            this.snackbar.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackbar.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackbar.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.snackbar.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.snackbar.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.snackbar.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackbar.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.snackbar.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.snackbar.SuccessOptions.IconLeftMargin = 12;
            this.snackbar.ViewsMargin = 7;
            this.snackbar.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snackbar.WarningOptions.ActionBorderRadius = 1;
            this.snackbar.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snackbar.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snackbar.WarningOptions.BackColor = System.Drawing.Color.White;
            this.snackbar.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.snackbar.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.snackbar.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snackbar.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.snackbar.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.snackbar.WarningOptions.IconLeftMargin = 12;
            this.snackbar.ZoomCloseIcon = true;
            // 
            // MainFrame
            // 
            this.MainFrame.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.MainFrame.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MainFrame.BackgroundImage")));
            this.MainFrame.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.MainFrame.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.MainFrame.BorderRadius = 0;
            this.MainFrame.BorderThickness = 0;
            this.MainFrame.Controls.Add(this.p_tabs);
            this.MainFrame.Controls.Add(this.p_header);
            this.MainFrame.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainFrame.Location = new System.Drawing.Point(0, 0);
            this.MainFrame.Margin = new System.Windows.Forms.Padding(0);
            this.MainFrame.Name = "MainFrame";
            this.MainFrame.ShowBorders = true;
            this.MainFrame.Size = new System.Drawing.Size(916, 689);
            this.MainFrame.TabIndex = 1;
            // 
            // p_tabs
            // 
            this.p_tabs.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.p_tabs.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("p_tabs.BackgroundImage")));
            this.p_tabs.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.p_tabs.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.p_tabs.BorderRadius = 0;
            this.p_tabs.BorderThickness = 0;
            this.p_tabs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.p_tabs.Location = new System.Drawing.Point(0, 32);
            this.p_tabs.Name = "p_tabs";
            this.p_tabs.ShowBorders = true;
            this.p_tabs.Size = new System.Drawing.Size(916, 657);
            this.p_tabs.TabIndex = 1;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 25;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "0";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 20;
            this.bunifuButton1.ColorContrastOnHover = 20;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton1.Font = new System.Drawing.Font("Ebrima", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(1, 0, 0, 0);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 5;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.IconSize = 20;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.IdleBorderRadius = 25;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(708, 3);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.MaximumSize = new System.Drawing.Size(26, 26);
            this.bunifuButton1.MinimumSize = new System.Drawing.Size(26, 26);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(40)))), ((int)(((byte)(49)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 25;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.onHoverState.BorderRadius = 25;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.BorderRadius = 25;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(221)))), ((int)(((byte)(222)))));
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnPressedState.BorderRadius = 25;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(34)))), ((int)(((byte)(37)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(26, 26);
            this.bunifuButton1.TabIndex = 37;
            this.bunifuButton1.Tag = "";
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(2, 0, 3, 2);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.BunifuButton1_Click);
            // 
            // sep_tools
            // 
            this.sep_tools.BackColor = System.Drawing.Color.Transparent;
            this.sep_tools.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sep_tools.BackgroundImage")));
            this.sep_tools.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sep_tools.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.sep_tools.Dock = System.Windows.Forms.DockStyle.Right;
            this.sep_tools.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.sep_tools.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.sep_tools.LineThickness = 1;
            this.sep_tools.Location = new System.Drawing.Point(685, 3);
            this.sep_tools.Name = "sep_tools";
            this.sep_tools.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.sep_tools.Size = new System.Drawing.Size(23, 26);
            this.sep_tools.TabIndex = 38;
            // 
            // MainWindow
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(57)))), ((int)(((byte)(63)))));
            this.ClientSize = new System.Drawing.Size(916, 689);
            this.Controls.Add(this.MainFrame);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.Name = "MainWindow";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "DOT";
            this.p_header.ResumeLayout(false);
            this.p_header.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pb_header)).EndInit();
            this.MainFrame.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel p_header;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton bttn_fullscreen;
        private Bunifu.UI.WinForms.BunifuSeparator sep_tools__windowbuttons;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton bttn_mini;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton bttn_maxmini;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton bttn_exit;
        private Bunifu.UI.WinForms.BunifuSnackbar snackbar;
        private Bunifu.UI.WinForms.BunifuPanel MainFrame;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.PictureBox pb_header;
        private Bunifu.UI.WinForms.BunifuPanel p_tabs;
        private Bunifu.UI.WinForms.BunifuSeparator sep_icon__title;
        private System.Windows.Forms.Label label1;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton bttn_zoomin;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton bttn_zoomout;
        private Bunifu.UI.WinForms.BunifuSeparator sep_tools;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
    }
}